[project]
name = "rag-based-medical-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Somnath-ganguly", email = "somnath.ganguly.cse@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.3",
]

[project.scripts]
rag-based-medical-chatbot = "rag_based_medical_chatbot:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
